#!/bin/bash
: "${ZBASH_COMMONS_SRC_PATH:="$(dirname "${BASH_SOURCE[0]}")/.."}"

# Loading the compile scripts
source "$ZBASH_COMMONS_SRC_PATH/load"

: "${ZBASH_COMMONS_OUTPUT:="$1"}"
: "${ZBASH_COMMONS_OUTPUT:="$(make_temp_path /tmp/zbash-commons-compiled-XXXXXXX.sh)"}"
log:sep "Compiling sources to $ZBASH_COMMONS_OUTPUT"

function compile_scripts() {
  local compiled=()
  for file in $ZBASH_COMMONS_SRC_PATH/scripts/*; do
    compiled+=("$(cat $file)")
    assert $? "Error while loading lib file: $file" || return $?
  done
  printf "%s" "$(join_by $'\n' "${compiled[@]}")"
}

compile_scripts >$ZBASH_COMMONS_OUTPUT
assert $? "Failed to compile scripts" || exit $?

log "Compilation complete with $(wc -l $ZBASH_COMMONS_OUTPUT) lines"
